# Generated by Django 3.1.4 on 2020-12-11 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_schedule_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end_datetime',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start_datetime',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
