# Generated by Django 3.1.4 on 2020-12-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201211_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_date',
        ),
    ]
